[package]
name = "openai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openai-api-rs = "0.1.5"
tokio = { version = "1.12.0", features = ["full"] } # for our async runtime   